POST http://localhost:3003/user
Content-Type: application/json

{
    "name":"Guilherme",
    "email":"gui@gmail.com",
    "password":"gui123"
}

##
GET http://localhost:3003/users
##

POST http://localhost:3003/products
Content-Type: application/json

{
    "name":"Notebook",
    "price":5000.10,
    "image_url":"https://i.picsum.photos/id/0/5616/3744.jpg?hmac=3GAAioiQziMGEtLbfrdbcoenXoWAW-zlyEAMkfEdBzQ"
}

##
GET http://localhost:3003/products
